services:
  app_notifications_test:
    build: 
      context: ./notifications # Ruta al directorio donde está el Dockerfile del monolito notifications
      dockerfile: Dockerfile.test
    mem_limit: 512m
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notifications_dbtest:5432/challengenoti_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mariano
      SPRING_JPA_DDL_AUTO: create-drop
      SECURITY_JWT_SECRET: TESTtr7fWPzg2+H+hKbSSFWfLo34bqr8oJZanLpBrs6VTuI=
      SECURITY_JWT_ISSUER: Main
      SECURITY_JWT_TTL_MILLIS: 3600000
      SPRING_PROFILES_ACTIVE: test
    depends_on:
      notifications_dbtest:
        condition: service_healthy
    command: >
      sh -c "
      ./mvnw clean verify -Dtest=com.api.notifications.ControllerTestSuite &&
      echo '---------------- TESTS TERMINADOS ----------------'
      "

  notifications_dbtest:
    image: postgres:16    
    environment:
      POSTGRES_DB: challengenoti_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mariano
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
